trainer:
  class_path: "lightning.Trainer"
  init_args:
    max_epochs: 200
    gradient_clip_val: 0.1
    gradient_clip_algorithm: "norm"
model:
  class_path: "train.li_nerf.LiNerf"
  init_args:
    model:
      class_path: "nerf.nerf.nerf.Nerf"
      init_args:
        Lp: 10
        Ld: 4
        low_res_bins: 64
        high_res_bins: 128
        homogeneous_projection: false
datamodule:
  class_path: "datamodule.datamodule.DataModule"
  init_args:
    dataset_path: "/database/nerf/v_data/dense"
    split: true
    batch: 1024
    num_workers: 16
    width: 320
    height: 320
visualizer:
  samples: 256
  threshold: 10
  name: "output_mesh"
  x_limit: [-0.5, 0.5]
  y_limit: [-0.5, 0.5]
  z_limit: [-0.5, 0.5]