trainer:
  class_path: "lightning.Trainer"
  init_args:
    max_epochs: 200
    gradient_clip_val: 0.1
    gradient_clip_algorithm: "norm"
model:
  class_path: "train.li_nerf.LiNerf"
  init_args:
    model:
      class_path: "nerf.nerf.nerf_hypothesis.Nerf"
      init_args:
        Lp: 10
        Ld: 4
        bins: 32
        homogeneous_projection: true
        mixtures: 4
datamodule:
  class_path: "datamodule.datamodule.DataModule"
  init_args:
    dataset_path: "/database/nerf/v_data/dense"
    split: false
    batch: 1024
    num_workers: 16
    width: 320
    height: 320
visualizer:
  samples: 256
  threshold: 50
  name: "output_mesh"
  x_limit: [-0.3, 0.3]
  y_limit: [-0.3, 0.3]
  z_limit: [-0.2, 0.4]