trainer:
  class_path: "lightning.Trainer"
  init_args:
    max_epochs: 200
    gradient_clip_val: 0.1
    gradient_clip_algorithm: "norm"
model:
  class_path: "train.li_nerf.LiNerf"
  init_args:
    model:
      class_path: "nerf.neus.nerf.Nerf"
      init_args:
        s_inv_log_init: -3.0
        Lp: 10
        Ld: 4
        low_res_bins: 64
        high_res_bins: 128
        homogeneous_projection: true
        biased_integration: true
        ray_boundary: 
          class_path: nerf.util.boundary.RayBoundaryLimits
datamodule:
  class_path: "datamodule.datamodule.DataModule"
  init_args:
    dataset_path: "/database/nerf/statue/exported/dense"
    split: true
    batch: 1024
    num_workers: 16
    width: 320
    height: 320
visualizer:
  samples: 512
  threshold: 0
  name: "output_mesh"
  x_limit: [-1, 1]
  y_limit: [-1, 1]
  z_limit: [-1, 1]